/*
-----------------------------------------------------------------------------
Filename:    tw_demo.h
-----------------------------------------------------------------------------

This source file is generated by the Ogre AppWizard.

Check out: http://conglomerate.berlios.de/wiki/doku.php?id=ogrewizards

Based on the Example Framework for OGRE
(Object-oriented Graphics Rendering Engine)

Copyright (c) 2000-2007 The OGRE Team
For the latest info, see http://www.ogre3d.org/

You may use this sample code for anything you like, it is not covered by the
LGPL like the rest of the OGRE engine.
-----------------------------------------------------------------------------
*/
#ifndef __tw_demo_h_
#define __tw_demo_h_
#define _WIN32_WINNT	0x0501

#include "BaseApplication.h"
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
#include "res/resource.h"
#endif
#include <CEGUI.h>
#include <CEGUISystem.h>
#include <CEGUISchemeManager.h>
#include <OgreCEGUIRenderer.h>
#include "MultiMouse.h"
#include <hash_map>
#include "TouchableNode.h"
using namespace std;


class tw_demoApp : public BaseApplication, public Ogre::Singleton<tw_demoApp>
{
public:
	Vector3 m_Points[4];
	int m_npoints;
	RaySceneQuery* mpRayQuery;
	HWND m_hwnd;
	WNDPROC mpfnWndProc;
	MultiMouse* m_MultiMice;
	HashMap< string, TouchableNode*> m_TouchableNodes;

	tw_demoApp(void);
	virtual ~tw_demoApp(void);

public:
	void MultiMouseMoved(Mouse&);
	void MultiMouseLPressed(Mouse&);
	void MultiMouseLReleased(Mouse&);
	virtual void createScene(void);
	virtual void loadResources();
	bool frameStarted(const FrameEvent& evt);
	void CreateImages();
	void DebugPoint(Vector3 pos,SceneNode* parentSn = tw_demoApp::getSingleton().mSceneMgr->getRootSceneNode(),float scale = 0.01f);
	SceneNode* CastRay(float x,float y, Vector3& intersection_point );
	static LRESULT wndProc(HWND hwnd,UINT msg, WPARAM wparam,LPARAM lparam);
	static BOOL CALLBACK EnumThreadWndProc(HWND hwnd,LPARAM lParam);

};


#endif // #ifndef __tw_demo_h_